# PatternCount(Text, Pattern)
#   count ← 0
#   for i ← 0 to |Text| − |Pattern|
#     if Text(i, |Pattern|) = Pattern
#       count ← count + 1
#   return count
PatternCount <- function(Text, Pattern) {
  count <- 0
  
  for (i in 1:(nchar(Text) - nchar(Pattern))) {
    if (substring(Text, i, i + nchar(Pattern) - 1) == Pattern) {
      count <- count + 1
    }
  }
  
  return(count)
}

# Text <- 'AGGTAGCTGCTTCTCGAGGTAGCTTTACGCTAGGTAGCCCATAGACCAGGTAGCTCAGGGAGGTAGCAGGTAGCCAAGGTAGCACGTCTCAGGTAGCGAGGTAGCGATAGGTAGCAGGTAGCGTAGGTAGCCAGGTAGCTAGGTAGCACACGTAGGTAGCTAGGTAGCATAAAATCCATCAGGTAGCCTGAGGTAGCCAGGTAGCAGGTAGCAGGTAGCTTCTGAGGTAGCTGAATGAGGTAGCAAGTGAGGTAGCTGGAGGTAGCAAGGTAGCAGGTAGCAGGTAGCTAAGGTAGCATAGGTAGCCCCAAAGGTAGCTAGCAGAGGTAGCACCGGGGGGTTTGTTAGGTAGCAAGCAGGTAGCTAGGTAGCAGGTAGCAGGTAGCTGCAGGTAGCGTAGGTAGCAGGTAGCATGTAAGGTAGCCTGAGGTAGCAGGTAGCTTGCGGAGGTAGCAGGTAGCAGGTAGCAGGTAGCAGGTAGCGAAGGTAGCATGAAATATGTCGTTGAAGGTAGCGGAAGGTAGCAATGCCAGGTAGCGCGAGGTAGCGAGGTAGCGGGAGGTAGCTAGGTAGCAGGTAGCAAATAGGTAGCAAGGTAGCTAGGTAGCTAGGTAGCCACTAGGTAGCAAGGTAGCCATTTTCAGGTAGCGGGAGGTAGCTGAACAAGGTAGCAGGTAGCAGGTAGCAGGTAGCGAGGTAGCAAGGTAGCGTAGGTAGCTCAGGTAGCGGTAGGTAGCGGATAAGGTAGCAGGTAGCTAGGTAGCTAGGTAGCGAGGTAGCCAAACAAGAGGTAGCTAGGTAGCTAGGAGGTAGCTAGGTAGCTTCTAAAGGTAGCAGGTAGCAGGTAGCAGGTAGCGAGGTAGCTATGAGGTAGCTAGGTAGCGCATCCACGTGATGAGGTAGCTAGGTAGCACTAGGTAGCTGTAAGGTAGCGATGAGGTAGCCATCGTGGAAGGTAGCAAAAGGTAGCAAGGTAGCCTCAGAGGTAGCGTAGGTAGCACGCAGGTAGCA'
# Pattern <- 'AGGTAGCAG'
# print(PatternCount(Text, Pattern))

# FrequentWords(Text, k)
#   FrequentPatterns ← an empty set
#   for i ← 0 to |Text| − k
#     Pattern ← the k-mer Text(i, k)
#     Count(i) ← PatternCount(Text, Pattern)
#   maxCount ← maximum value in array Count
#   for i ← 0 to |Text| − k
#     if Count(i) = maxCount
#       add Text(i, k) to FrequentPatterns
#   remove duplicates from FrequentPatterns
#   return FrequentPatterns
FrequentWords <- function(Text, k) {
  FrequentPatterns <- character()
  Count <- integer(nchar(Text) - k + 1)
  
  for (i in 1:length(Count)) {
    Pattern <- substring(Text, i, i + k - 1)
    Count[i] <- PatternCount(Text, Pattern)
  }
  
  maxCount <- max(Count)
  
  for (i in 1:length(Count)) {
    if (Count[i] == maxCount) {
      FrequentPatterns <- c(FrequentPatterns, substring(Text, i, i + k - 1))
    }
  }
  
  FrequentPatterns <- unique(FrequentPatterns)
  return(FrequentPatterns)
}

# Text <- 'GGATACTCCACGGCCATGGGGATACTCCCCGCCCTGAATCGTTGAGCTCCGCCCTGAATCGTTGAGCTACGATTGATTACGGCCATGGACGATTGATTACGGCCATGGACGATTGATTGGATACTCCCCGCCCTGAACCGCCCTGAAACGGCCATGGCCGCCCTGAAACGATTGATTGGATACTCCACGGCCATGGGGATACTCCGGATACTCCTCGTTGAGCTTCGTTGAGCTACGATTGATTACGGCCATGGTCGTTGAGCTTCGTTGAGCTACGGCCATGGTCGTTGAGCTGGATACTCCGGATACTCCGGATACTCCACGATTGATTACGATTGATTGGATACTCCGGATACTCCGGATACTCCCCGCCCTGAAACGATTGATTACGGCCATGGACGGCCATGGGGATACTCCTCGTTGAGCTGGATACTCCTCGTTGAGCTGGATACTCCCCGCCCTGAATCGTTGAGCTGGATACTCCACGATTGATTCCGCCCTGAACCGCCCTGAAACGGCCATGGACGGCCATGGACGATTGATTACGATTGATTGGATACTCCACGGCCATGGCCGCCCTGAAACGATTGATTGGATACTCCTCGTTGAGCTCCGCCCTGAAACGATTGATTTCGTTGAGCTCCGCCCTGAAGGATACTCCCCGCCCTGAATCGTTGAGCTCCGCCCTGAACCGCCCTGAAACGGCCATGGCCGCCCTGAAACGATTGATTACGGCCATGGACGATTGATTCCGCCCTGAATCGTTGAGCTCCGCCCTGAAACGGCCATGGTCGTTGAGCTTCGTTGAGCTACGGCCATGGCCGCCCTGAATCGTTGAGCTGGATACTCCACGATTGATTACGGCCATGGGGATACTCCCCGCCCTGAAGGATACTCCACGGCCATGGCCGCCCTGAATCGTTGAGCTCCGCCCTGAAACGGCCATGGCCGCCCTGAAACGGCCATGGCCGCCCTGAACCGCCCTGAA'
# k <- 13
# print(paste(FrequentWords(Text, k), collapse = ' '))

# AAGCAAAGGTGGG
PatternToNumber <- function(Pattern) {
  tokens <- rev(strsplit(Pattern, NULL)[[1]])
  Number <- sum(4 ^ (grep('C', tokens) - 1))
  Number <- Number + sum(2 * 4 ^ (grep('G', tokens) - 1))
  Number <- Number + sum(3 * 4 ^ (grep('T', tokens) - 1))
  return(Number)
}

# PatternToNumber('ATGCAA')

NumberToPattern <- function(Number, k) {
  Pattern <- ''
  
  if (Number %in% 0:(4 ^ k - 1)) {
    
    Pattern <- as.character(rev((Number %% (4 * (k:1 + 1)) %/% (4 * k:1))))
    Pattern[Pattern == '0'] <- 'A'
    Pattern[Pattern == '1'] <- 'C'
    Pattern[Pattern == '2'] <- 'G'
    Pattern[Pattern == '3'] <- 'T'
    Pattern <- paste(Pattern, collapse = '')
  }
  
  return(Pattern)
}

NumberToPattern(123, 4)
